name: deploy-container

on:
  push:
    branches:
      - main
    # paths:
    #   - "packages/container/**" # Only run the workflow when the container/ directory is changed

defaults:
  run:
    working-directory: packages/container # essentially a `cd` command

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Enable AWS CLI usage
        uses: shinyinc/action-aws-cli@v1.2

      - name: Sync to AWS S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
